### PR TITLE
Drop Travis CI setting

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- Since the GitHub Action has been enabled on this repostiroy, I think it's time to drop Travis CI building.

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thanks for this! Do you mind dropping appveyor too?

**Comment by jcchavezs** [comment]
Also, do you mind removing the badges? Thanks a lot!

**Comment by peter279k** [comment]
> Also, do you mind removing the badges? Thanks a lot!

Done :).

**Comment by jcchavezs** [comment]
Thanks a lot again @peter279k!

**Pull request merged**
