### PR TITLE
Convert carrier key to string.

### PR DESCRIPTION
**Pull request by devin515**
strtolower(): Argument #1 ($string) must be of type string

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thanks for this! Are you getting any error because of that or a warning?

**Comment by devin515** [comment]
This is what happens when you test a header key with a number in it.

**Comment by jcchavezs** [comment]
I see. Thank you!

**Comment by huangdijia** [comment]
@jcchavezs When will the new version be released?

**Comment by huangdijia** [comment]
> I will cut a release today.

Thanks

**Comment by jcchavezs** [comment]
Done https://github.com/openzipkin/zipkin-php/releases/tag/3.1.0

**Pull request merged**
