### PR TITLE
fix: Correct inaccurate expression

### LINKED ISSUE #134: Inaccuracy in PercentageSampler
Implementation in `\Zipkin\Samplers\PercentageSampler::isSampled()` is a bit inaccurate:
```php
    public function isSampled($traceId)
    {
        return (mt_rand(0, 99) / 100) <= $this->rate;
    }
```
Given `$this->rate = 0.00` would still sample at 1%, while `$this->rate = 0.99` would already sample at 100%.

It should be sufficient to change operator from `<=` to `<`.

### PR DESCRIPTION
**Pull request by pauci**
Fixes #134

### CODE REVIEW

**Comment by jcchavezs** [comment]
Thank you!

**Comment by jcchavezs** [comment]
Are you using 1.x? I can do a new release with this change.

**Comment by pauci** [comment]
I'm using 1.3.4, but I made custom sampler already, so I'm ok.

**Comment by jcchavezs** [comment]
Good. Since this is a bug fix I will release 1.3.5 anyways.

**Pull request merged**
